# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iriverpla.ui'
#
# Created: Sat Dec  3 12:28:45 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(645, 432)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "iriverPLA v0.1.0", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.rootLabel = QtGui.QLabel(self.centralwidget)
        self.rootLabel.setText(QtGui.QApplication.translate("MainWindow", "Root:", None, QtGui.QApplication.UnicodeUTF8))
        self.rootLabel.setObjectName(_fromUtf8("rootLabel"))
        self.verticalLayout_5.addWidget(self.rootLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rootPathEntry = QtGui.QLineEdit(self.centralwidget)
        self.rootPathEntry.setObjectName(_fromUtf8("rootPathEntry"))
        self.horizontalLayout_3.addWidget(self.rootPathEntry)
        self.rootPathSelButton = QtGui.QPushButton(self.centralwidget)
        self.rootPathSelButton.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rootPathSelButton.setIcon(icon1)
        self.rootPathSelButton.setIconSize(QtCore.QSize(16, 16))
        self.rootPathSelButton.setObjectName(_fromUtf8("rootPathSelButton"))
        self.horizontalLayout_3.addWidget(self.rootPathSelButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.musicTreeLabel = QtGui.QLabel(self.layoutWidget)
        self.musicTreeLabel.setText(QtGui.QApplication.translate("MainWindow", "Music:", None, QtGui.QApplication.UnicodeUTF8))
        self.musicTreeLabel.setObjectName(_fromUtf8("musicTreeLabel"))
        self.verticalLayout_4.addWidget(self.musicTreeLabel)
        self.musicTreeView = QtGui.QTreeView(self.layoutWidget)
        self.musicTreeView.setObjectName(_fromUtf8("musicTreeView"))
        self.verticalLayout_4.addWidget(self.musicTreeView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.addButton = QtGui.QToolButton(self.layoutWidget)
        self.addButton.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon2)
        self.addButton.setIconSize(QtCore.QSize(24, 24))
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.verticalLayout_2.addWidget(self.addButton)
        self.delButton = QtGui.QToolButton(self.layoutWidget)
        self.delButton.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/del.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delButton.setIcon(icon3)
        self.delButton.setObjectName(_fromUtf8("delButton"))
        self.verticalLayout_2.addWidget(self.delButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.musicListLabel = QtGui.QLabel(self.layoutWidget1)
        self.musicListLabel.setText(QtGui.QApplication.translate("MainWindow", "Music:", None, QtGui.QApplication.UnicodeUTF8))
        self.musicListLabel.setObjectName(_fromUtf8("musicListLabel"))
        self.verticalLayout_3.addWidget(self.musicListLabel)
        self.musicListView = QtGui.QListView(self.layoutWidget1)
        self.musicListView.setObjectName(_fromUtf8("musicListView"))
        self.verticalLayout_3.addWidget(self.musicListView)
        self.verticalLayout_6.addWidget(self.splitter)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.playlistLabel = QtGui.QLabel(self.centralwidget)
        self.playlistLabel.setText(QtGui.QApplication.translate("MainWindow", "Playlist:", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistLabel.setObjectName(_fromUtf8("playlistLabel"))
        self.verticalLayout.addWidget(self.playlistLabel)
        self.playlistEntry = QtGui.QLineEdit(self.centralwidget)
        self.playlistEntry.setObjectName(_fromUtf8("playlistEntry"))
        self.verticalLayout.addWidget(self.playlistEntry)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.saveListButton = QtGui.QPushButton(self.centralwidget)
        self.saveListButton.setText(QtGui.QApplication.translate("MainWindow", "Save List", None, QtGui.QApplication.UnicodeUTF8))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveListButton.setIcon(icon4)
        self.saveListButton.setIconSize(QtCore.QSize(16, 16))
        self.saveListButton.setObjectName(_fromUtf8("saveListButton"))
        self.horizontalLayout.addWidget(self.saveListButton)
        self.clearListButton = QtGui.QPushButton(self.centralwidget)
        self.clearListButton.setText(QtGui.QApplication.translate("MainWindow", "Clear List", None, QtGui.QApplication.UnicodeUTF8))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearListButton.setIcon(icon5)
        self.clearListButton.setIconSize(QtCore.QSize(16, 16))
        self.clearListButton.setObjectName(_fromUtf8("clearListButton"))
        self.horizontalLayout.addWidget(self.clearListButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.createButton = QtGui.QPushButton(self.centralwidget)
        self.createButton.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/create.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createButton.setIcon(icon6)
        self.createButton.setIconSize(QtCore.QSize(16, 16))
        self.createButton.setObjectName(_fromUtf8("createButton"))
        self.horizontalLayout.addWidget(self.createButton)
        self.quitButton = QtGui.QPushButton(self.centralwidget)
        self.quitButton.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitButton.setIcon(icon7)
        self.quitButton.setIconSize(QtCore.QSize(16, 16))
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.horizontalLayout.addWidget(self.quitButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 645, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_list = QtGui.QAction(MainWindow)
        self.actionOpen_list.setIcon(icon1)
        self.actionOpen_list.setText(QtGui.QApplication.translate("MainWindow", "Open list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_list.setObjectName(_fromUtf8("actionOpen_list"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pref.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon8)
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionIriverPLA_Help = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIriverPLA_Help.setIcon(icon9)
        self.actionIriverPLA_Help.setText(QtGui.QApplication.translate("MainWindow", "iriverPLA Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIriverPLA_Help.setObjectName(_fromUtf8("actionIriverPLA_Help"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon10)
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.actionAbout_iriverPLA = QtGui.QAction(MainWindow)
        self.actionAbout_iriverPLA.setIcon(icon10)
        self.actionAbout_iriverPLA.setText(QtGui.QApplication.translate("MainWindow", "About iriverPLA", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_iriverPLA.setObjectName(_fromUtf8("actionAbout_iriverPLA"))
        self.actionSave_list = QtGui.QAction(MainWindow)
        self.actionSave_list.setIcon(icon4)
        self.actionSave_list.setText(QtGui.QApplication.translate("MainWindow", "Save list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_list.setObjectName(_fromUtf8("actionSave_list"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setIcon(icon7)
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionCreate_PLA = QtGui.QAction(MainWindow)
        self.actionCreate_PLA.setIcon(icon6)
        self.actionCreate_PLA.setText(QtGui.QApplication.translate("MainWindow", "Create PLA", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_PLA.setObjectName(_fromUtf8("actionCreate_PLA"))
        self.actionClear_list = QtGui.QAction(MainWindow)
        self.actionClear_list.setIcon(icon5)
        self.actionClear_list.setText(QtGui.QApplication.translate("MainWindow", "Clear list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_list.setObjectName(_fromUtf8("actionClear_list"))
        self.menuFile.addAction(self.actionOpen_list)
        self.menuFile.addAction(self.actionSave_list)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionCreate_PLA)
        self.menuTools.addAction(self.actionClear_list)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionIriverPLA_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionAbout_iriverPLA)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen_list)
        self.toolBar.addAction(self.actionSave_list)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_list)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreate_PLA)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIriverPLA_Help)
        self.toolBar.addAction(self.actionAbout_iriverPLA)
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

import icons_rc
